# Generated by Django 4.1.2 on 2022-10-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceLists",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "original_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("oem_number", models.CharField(blank=True, max_length=255, null=True)),
                ("stock", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
