# Generated by Django 4.1.2 on 2022-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_pricelist_supplier_delete_pricelists_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
