# Generated by Django 4.1.2 on 2022-10-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_supplier_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="skip_rows",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
