# Generated by Django 4.1.2 on 2022-10-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_supplier_weight_alter_supplier_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="weight",
            field=models.IntegerField(default=10, help_text="Вес поставщика"),
        ),
    ]
