# Generated by Django 4.1.2 on 2022-11-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_supplier_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="updated_price",
            field=models.DateTimeField(blank=True),
        ),
    ]
