# Generated by Django 4.1.2 on 2022-11-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_supplier_name_rus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="name_rus",
            field=models.CharField(
                default="Change me",
                help_text="Наименование поставщика, на русском как душе угодно",
                max_length=255,
            ),
        ),
    ]
